/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Grafica;

import com.toedter.calendar.JDateChooser;
import Logica.GestorParqueadero;
import dto.RegistroIngreso;
import dto.Vehiculo;
import static java.lang.System.exit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valentina
 */
public class Ventana extends javax.swing.JFrame {
    private JDateChooser cjFechah;
    private DefaultTableModel modelTabla;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        cjFechah = new JDateChooser();
        getContentPane().add(cjFechah);
        cjFechah.setBounds(60, 125, 80, 18);
        this.cargarVehiculos();
        PanelEntrada.setVisible(false);
        PanelSalida.setVisible(false);
        cjFechah.setVisible(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PanelEntrada = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tvehiculos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cjplaca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cjidentificacion = new javax.swing.JTextField();
        Bborrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Bentrada = new javax.swing.JButton();
        Bsalida = new javax.swing.JButton();
        PanelSalida = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Cjplaca = new javax.swing.JTextField();
        Bbuscar = new javax.swing.JButton();
        Bsalir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        PanelEntrada.setBackground(new java.awt.Color(204, 255, 255));

        Tvehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tvehiculos);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha");

        jLabel4.setText("Placa");

        cjplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjplacaActionPerformed(evt);
            }
        });

        jLabel5.setText("Identificación");

        cjidentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjidentificacionActionPerformed(evt);
            }
        });

        Bborrar.setText("Borrar");
        Bborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEntradaLayout = new javax.swing.GroupLayout(PanelEntrada);
        PanelEntrada.setLayout(PanelEntradaLayout);
        PanelEntradaLayout.setHorizontalGroup(
            PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntradaLayout.createSequentialGroup()
                .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEntradaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEntradaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelEntradaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cjplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelEntradaLayout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cjidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelEntradaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bborrar)
                .addGap(66, 66, 66))
        );
        PanelEntradaLayout.setVerticalGroup(
            PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntradaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cjplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEntradaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cjidentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelEntradaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Bborrar))
                .addGap(67, 67, 67))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Gestion Parqueadero");

        Bentrada.setBackground(new java.awt.Color(204, 255, 255));
        Bentrada.setText("Entrada");
        Bentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BentradaActionPerformed(evt);
            }
        });

        Bsalida.setBackground(new java.awt.Color(153, 255, 255));
        Bsalida.setText("Salida");
        Bsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsalidaActionPerformed(evt);
            }
        });

        PanelSalida.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setText("Placa");

        jLabel6.setText("Salida del vehiculo");

        Cjplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CjplacaActionPerformed(evt);
            }
        });

        Bbuscar.setText("Buscar");
        Bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSalidaLayout = new javax.swing.GroupLayout(PanelSalida);
        PanelSalida.setLayout(PanelSalidaLayout);
        PanelSalidaLayout.setHorizontalGroup(
            PanelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSalidaLayout.createSequentialGroup()
                .addGroup(PanelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSalidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(Cjplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelSalidaLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel6))
                    .addGroup(PanelSalidaLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Bbuscar)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        PanelSalidaLayout.setVerticalGroup(
            PanelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(PanelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Cjplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(Bbuscar)
                .addContainerGap())
        );

        Bsalir.setText("Salir");
        Bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bentrada)
                                .addGap(48, 48, 48)
                                .addComponent(Bsalida)
                                .addGap(204, 204, 204)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(PanelSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Bsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Bsalir))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addComponent(PanelSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bentrada)
                            .addComponent(Bsalida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(821, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cjidentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjidentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjidentificacionActionPerformed

    private void cjplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjplacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjplacaActionPerformed

    private void BsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalirActionPerformed
        Salir();
    }//GEN-LAST:event_BsalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        crearIngreso();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BentradaActionPerformed
        PanelEntrada.setVisible(true);
        cjFechah.setVisible(true);
        
        PanelSalida.setVisible(false);
    }//GEN-LAST:event_BentradaActionPerformed

    private void BsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalidaActionPerformed
        // TODO add your handling code here:
        PanelEntrada.setVisible(false);
        
        PanelSalida.setVisible(true);
        cjFechah.setVisible(false);
    }//GEN-LAST:event_BsalidaActionPerformed

    private void CjplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CjplacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CjplacaActionPerformed

    private void BbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbuscarActionPerformed
        // TODO add your handling code here:
        buscarVehiculo();
        
    }//GEN-LAST:event_BbuscarActionPerformed

    private void BborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BborrarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BborrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    private void crearIngreso(){
        
        
        String identificacion = cjidentificacion.getText();
        Date fechaHoraIngreso = cjFechah.getDate();
        String placa = cjplaca.getText();
        
        GestorParqueadero g = new GestorParqueadero();
        RegistroIngreso c = g.crearIngreso(placa, identificacion, fechaHoraIngreso);
       
        //for
        if (c!=null ){
            cargarVehiculos();
            JOptionPane.showMessageDialog(this, "Registro ingreso ->"+c);
            
        }else{
            JOptionPane.showMessageDialog(this, " no registro ingreso");
        }
        
        
        
    }
    
    
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bborrar;
    private javax.swing.JButton Bbuscar;
    private javax.swing.JButton Bentrada;
    private javax.swing.JButton Bsalida;
    private javax.swing.JButton Bsalir;
    private javax.swing.JTextField Cjplaca;
    private javax.swing.JPanel PanelEntrada;
    private javax.swing.JPanel PanelSalida;
    private javax.swing.JTable Tvehiculos;
    private javax.swing.JTextField cjidentificacion;
    private javax.swing.JTextField cjplaca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private void cargarVehiculos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("CODIGO");
        modelo.addColumn("FECHA Y HORA");
        modelo.addColumn("IDENTIFICACIÓN");
        modelo.addColumn("PLACA");
        
        
        GestorParqueadero gestor = new GestorParqueadero();
        Map<String, RegistroIngreso> lista = gestor.obtenerLista();
        for (Map.Entry<String, RegistroIngreso> dato  : lista.entrySet()) {
            RegistroIngreso ri = dato.getValue();
            Object[] datos = {
                ri.getCodigo(),
                utilidades.util.convertirDateString(ri.obtenerFechaHoraIngreso()),
                ri.obtenerVehiculo().obtenerIdentificacion(),
                ri.obtenerVehiculo().obtenerPlaca()
                
            };
            modelo.addRow(datos);
            
        }
        this.Tvehiculos.setModel(modelo);
    }
    
    public void Salir(){
       exit(0);
    }
    private void buscarVehiculo(){
        
        String placa=Cjplaca.getText();
        GestorParqueadero gestor = new GestorParqueadero();
        Map<String,RegistroIngreso > vehiculos= gestor.obtenerLista();
        
        Iterator<String> it = vehiculos.keySet().iterator();

        while(it.hasNext()){
                String clave = it.next();
                RegistroIngreso vehiculo = vehiculos.get(clave);

                if(vehiculo.obtenerVehiculo().obtenerPlaca().equals(placa)){
                    
                    JOptionPane.showMessageDialog(this, " se encontro el vehiculo de placa: "+placa+"y debe pagar " + calcularValorPagar(vehiculo));
                    return;
                }
        }
        JOptionPane.showMessageDialog(this, " No se encontro vehiculo");
    }
    
   private int calcularValorPagar(RegistroIngreso vehiculo){
       int valorPagar=0;
       
       Long fechaIngreso=vehiculo.obtenerFechaHoraIngreso().getTime();
       Long diferencia=fechaIngreso-new Date().getTime();
                    
       long days=diferencia/(1000*60*60*24);
       
       if(days < -1){
          valorPagar= (int)(days*20000)* -1;
       }else
       {
           int horaInicio=vehiculo.obtenerFechaHoraIngreso().getHours();
           int horaFinal=new Date().getHours();
           int difHora=horaInicio-horaFinal;
           valorPagar=(difHora*4600)* -1;
       }
       
       
       return valorPagar;
   }

}


